import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { applyExclusions } from "../src/audit/exclusions.js";

let repo: string;

function git(...args: string[]): void {
  execFileSync("git", args, { cwd: repo, stdio: "ignore" });
}

function addFile(relPath: string, content = "export const x = 1;\n"): void {
  const abs = join(repo, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}

beforeAll(() => {
  repo = mkdtempSync(join(tmpdir(), "vibecheck-excl-"));
  git("init", "-q");
  git("config", "user.email", "test@example.com");
  git("config", "user.name", "Test");

  addFile("src/app.ts");
  addFile("src/util.ts");
  addFile("dist/bundle.js");
  addFile("vendor/lib.js");
  addFile("pnpm-lock.yaml", "lockfileVersion: 9\n");
  addFile("proto/service_pb2.py");
  addFile("api/types.gen.ts");
  addFile("assets/app.min.js");
  addFile("tests/__snapshots__/app.test.ts.snap");
  addFile("db/migrations/001_init.sql");
  addFile(
    "src/parser.ts",
    "// @generated by parser-gen v2\nexport const table = [];\n",
  );
  addFile(
    "src/schema.ts",
    "/* AUTO-BUILT — DO NOT EDIT */\nexport const schema = {};\n",
  );
  addFile(
    "src/deep-marker.ts",
    "line1\nline2\nline3\nline4\nline5\nline6 DO NOT EDIT\n",
  );
  addFile("attributed/gen.ts");
  addFile("attributed/vendored.ts");
  addFile(
    ".gitattributes",
    "attributed/gen.ts linguist-generated\nattributed/vendored.ts linguist-vendored=true\n",
  );

  git("add", "-A");
  git("commit", "-q", "-m", "fixture");
});

afterAll(() => rmSync(repo, { recursive: true, force: true }));

function trackedFiles(): string[] {
  return execFileSync("git", ["ls-files", "-z"], {
    cwd: repo,
    encoding: "utf-8",
  })
    .split("\0")
    .filter(Boolean);
}

describe("applyExclusions", () => {
  it("excludes each rule class and keeps real source", () => {
    const { kept, excluded } = applyExclusions(repo, trackedFiles());
    const reasons = new Map(excluded.map((e) => [e.path, e.reason]));

    expect(kept).toContain("src/app.ts");
    expect(kept).toContain("src/util.ts");
    // A marker beyond the first 5 lines does not exclude.
    expect(kept).toContain("src/deep-marker.ts");

    expect(reasons.get("dist/bundle.js")).toBe("path-convention");
    expect(reasons.get("vendor/lib.js")).toBe("path-convention");
    expect(reasons.get("pnpm-lock.yaml")).toBe("path-convention");
    expect(reasons.get("proto/service_pb2.py")).toBe("path-convention");
    expect(reasons.get("api/types.gen.ts")).toBe("path-convention");
    expect(reasons.get("assets/app.min.js")).toBe("path-convention");
    expect(reasons.get("tests/__snapshots__/app.test.ts.snap")).toBe(
      "path-convention",
    );
    expect(reasons.get("db/migrations/001_init.sql")).toBe("path-convention");
    expect(reasons.get("src/parser.ts")).toBe("generated-header");
    expect(reasons.get("src/schema.ts")).toBe("generated-header");
    expect(reasons.get("attributed/gen.ts")).toBe("gitattributes");
    expect(reasons.get("attributed/vendored.ts")).toBe("gitattributes");
  });

  it("is deterministic and sorted regardless of input order", () => {
    const files = trackedFiles();
    const forward = applyExclusions(repo, files);
    const reversed = applyExclusions(repo, [...files].reverse());
    expect(forward).toEqual(reversed);
    expect(forward.kept).toEqual([...forward.kept].sort());
  });

  it("excludes user-attested audit.exclude prefixes with reason config", () => {
    const { kept, excluded } = applyExclusions(repo, trackedFiles(), [
      "attributed",
    ]);
    const reasons = new Map(excluded.map((e) => [e.path, e.reason]));
    expect(reasons.get("attributed/gen.ts")).toBe("config");
    expect(reasons.get("attributed/vendored.ts")).toBe("config");
    expect(kept).toContain("src/app.ts");
  });

  it("still applies path and header rules outside a git repo", () => {
    const plain = mkdtempSync(join(tmpdir(), "vibecheck-nogit-"));
    try {
      const abs = join(plain, "gen.ts");
      writeFileSync(abs, "// @generated\n");
      writeFileSync(join(plain, "app.ts"), "export {};\n");
      const { kept, excluded } = applyExclusions(plain, [
        "gen.ts",
        "app.ts",
        "dist/x.js",
      ]);
      expect(kept).toEqual(["app.ts"]);
      expect(excluded.map((e) => e.path)).toEqual(["dist/x.js", "gen.ts"]);
    } finally {
      rmSync(plain, { recursive: true, force: true });
    }
  });
});
