/**
 * Agent briefing renderer (round-2, the promoted hand-written artifact)
 *
 * Round 1's revealed workflow is human-triages-agent-executes: the
 * maintainer's real output was a triage — real / noise / decision — plus
 * an execution order, hand-packaged for a planning agent. This module is
 * that packaging, automated. The human still makes every decision (the
 * briefing carries verdict commands, it never files them); alarm-only is
 * intact.
 *
 * Written to .vibecompact/out/agent-briefing.md on every run, and
 * regenerated by `vibecheck triage` after verdicts land.
 */

import { findingSlug } from "./evidence.js";
import { selectPackagedFindings, siblingPrecedents } from "./findings.js";
import type { AuditRunResult } from "./index.js";
import type { FileScore } from "./scoring.js";

/**
 * Findings the operator has not seen since their last acknowledgment.
 * Everything else was in a batch they already closed — it still fires,
 * but it must not be presented as fresh work (field round 2: a batch
 * announcing "25 new" packaged 45, most of them already triaged).
 */
function isNewSinceAck(result: AuditRunResult, score: FileScore): boolean {
  const fresh = new Set(result.ledger.newSinceAcknowledged);
  return score.firingLanes.some((f) =>
    fresh.has(`${f.lane}:${score.path}`),
  );
}

function precedentNote(
  result: AuditRunResult,
  path: string,
  lanes: string[],
): string {
  const count = new Set(
    lanes.flatMap((lane) =>
      siblingPrecedents(result, path, lane).map((v) => v.fingerprint),
    ),
  ).size;
  return count > 0
    ? ` · precedent: ${count} sibling verdict${count === 1 ? "" : "s"} (see package)`
    : "";
}

function laneAction(
  result: AuditRunResult,
  lane: string,
  path: string,
): string {
  switch (lane) {
    case "size":
      return "split along responsibility boundaries; add a test before moving logic";
    case "arrival":
      return "add at least one test whose import path reaches this file before changing it further";
    case "deadcode": {
      const entry = result.lanes.deadcode?.entries.find((e) => e.path === path);
      if (entry?.unusedFile) {
        return "verify unreferenced repo-wide (string imports, dynamic loading), then delete the file";
      }
      const internal = entry?.deadDetail.some((d) => d.internalUse === true);
      const dead = entry?.deadDetail.some((d) => d.internalUse === false);
      if (internal && dead) {
        return "un-export the items marked as internally used; delete the rest after verifying no dynamic consumers";
      }
      if (internal) {
        return "un-export the flagged items — they are used inside the file; only the export keyword is unconsumed";
      }
      return "verify each flagged export is unconsumed, then delete it";
    }
    case "duplication":
      return "extract the shared block into one module (clone partners in audit.json)";
    case "smells":
      return "replace any-typed identifiers with concrete types";
    case "consistency": {
      const entry = result.lanes.consistency?.entries.find(
        (e) => e.path === path,
      );
      if (entry?.copyArtifactOf)
        return `merge back into \`${entry.copyArtifactOf}\` or delete the copy`;
      if (entry?.orphan) return "verify unreachable, then delete";
      if (entry?.minorityOf)
        return `migrate to the package's majority provider (${entry.minorityOf})`;
      if (entry?.cycleSize) return "break the import cycle";
      return "align with the repo's dominant convention";
    }
    default:
      return "inspect and decide";
  }
}

function verdictCommands(offender: FileScore): string[] {
  return offender.firingLanes.map(
    (f) =>
      `vibecheck wontfix|noise|justify "${f.lane}:${offender.path}" --reason "..."`,
  );
}

/**
 * High-confidence deletion candidates: below-gate singles included —
 * deletion is the one action where a single strong state signal
 * (verified orphan, whole-file dead) is directly actionable.
 */
export function deletionCandidates(
  result: AuditRunResult,
): { path: string; reason: string }[] {
  const out = new Map<string, string>();
  for (const entry of result.lanes.consistency?.entries ?? []) {
    if (entry.orphan) {
      out.set(entry.path, "orphaned — zero import fan-in, no declared entry point");
    }
  }
  for (const entry of result.lanes.deadcode?.entries ?? []) {
    if (entry.unusedFile) {
      out.set(
        entry.path,
        (out.has(entry.path) ? out.get(entry.path) + "; " : "") +
          "knip: entire file unreferenced",
      );
    }
  }
  const suppressed = new Set(
    result.ledger.suppressed.map((s) => s.fingerprint.split(":").slice(1).join(":")),
  );
  return [...out.entries()]
    .filter(([path]) => !suppressed.has(path))
    .map(([path, reason]) => ({ path, reason }))
    .sort((a, b) => (a.path < b.path ? -1 : 1));
}

export function renderAgentBriefing(result: AuditRunResult): string {
  const deletions = deletionCandidates(result);
  const lines: string[] = [
    "# vibeCompact — agent briefing",
    "",
    `Anchor: \`${result.anchorSha?.slice(0, 12) ?? "no git"}\` (${result.trends.entry.at.slice(0, 10)}). ` +
      "Generated with the audit report; findings below are corroborated by ≥2 independent lanes unless marked otherwise.",
    "",
    "## Ground rules",
    "",
    "- Fixes need no ceremony: land a commit touching a flagged file and the next audit stamps it `fixed` automatically. Partial progress shows as **improving**.",
    "- Findings you judge wrong get verdicts, not workarounds — the commands are attached to each finding. Verdicts are maintainer decisions; confirm with the human before filing one.",
    // Only promise a verification section when packages actually carry
    // one (round-7: this line pointed at nothing on runs with no
    // deletion candidates).
    deletions.length > 0
      ? "- Do not delete anything without resolving the pre-run verification section on its deletion package."
      : "- Do not delete anything without verifying reachability yourself first: string references, dynamic imports, runner and workflow configs.",
  ];

  for (const [lane, rate] of Object.entries(result.saturatedLanes)) {
    lines.push(
      `- Trust note: the ${lane} lane is repo-saturated (${Math.round(rate * 100)}% firing) and muted from corroboration this run.`,
    );
  }
  for (const pair of (result.lanes.duplication?.dirPairs ?? []).slice(0, 3)) {
    lines.push(
      `- Structure drift: \`${pair.dirA}/\` ↔ \`${pair.dirB}/\` share ${pair.lines} duplicated lines (${pair.filePairs} file pair${pair.filePairs === 1 ? "" : "s"}) — one reads as a drifted copy of the other. Reconcile the pair; per-file fixes will not close it.`,
    );
  }
  if (result.coverageGaps.length > 0) {
    lines.push(
      `- Coverage warning: ${result.coverageGaps.length} of ${result.lanesPlanned.length} planned lanes unavailable or degraded (${result.coverageGaps.map((g) => g.lane).join(", ")}). ` +
        "Corroboration was weakened this run — an empty corroborated section is a coverage statement, and single-lane findings deserve more weight than usual.",
    );
  }

  const ordered = [
    ...result.bestFirstTargets,
    ...result.worstOffenders.filter(
      (o) => !result.bestFirstTargets.some((t) => t.path === o.path),
    ),
  ];
  if (ordered.length > 0) {
    lines.push(
      "",
      "## Corroborated work items (execution order: smallest blast radius first)",
    );
    for (const [index, offender] of ordered.entries()) {
      lines.push(
        "",
        `### ${index + 1}. \`${offender.path}\``,
        "",
        `- Firing: ${offender.firingLanes.map((f) => f.lane).join(" + ")} (${offender.applicableLanes.length} lanes applicable)`,
      );
      for (const firing of offender.firingLanes) {
        lines.push(
          `- ${firing.lane}: ${laneAction(result, firing.lane, offender.path)}`,
        );
      }
      const dead = result.lanes.deadcode?.entries.find(
        (e) => e.path === offender.path,
      );
      if (dead && dead.deadDetail.length > 0) {
        const names = dead.deadDetail.slice(0, 5).map((d) => d.name).join(", ");
        lines.push(
          `- dead surface: ${names}${dead.deadDetail.length > 5 ? ` (+${dead.deadDetail.length - 5} more)` : ""}`,
        );
      }
      lines.push(
        `- **Evidence package** (exact symbols, ranges, verification): \`.vibecompact/findings/${findingSlug(offender.path)}.md\``,
      );
      lines.push(`- If wrong or accepted: \`${verdictCommands(offender)[0]}\``);
    }
  } else {
    lines.push(
      "",
      "## Corroborated work items",
      "",
      "None pass the ≥2-lane gate this run.",
    );
  }

  const { singles, droppedByLane } = selectPackagedFindings(result);
  if (singles.length > 0) {
    lines.push(
      "",
      "## Single-lane findings (one signal each — weigh accordingly)",
      "",
      "Each has a full evidence package in `.vibecompact/findings/`.",
      "",
    );
    const freshSingles = singles.filter((x) => isNewSinceAck(result, x));
    const seenSingles = singles.filter((x) => !isNewSinceAck(result, x));
    if (freshSingles.length > 0 && seenSingles.length > 0) {
      lines.push(
        `**New since your last acknowledged batch: ${freshSingles.length}.** ` +
          `${seenSingles.length} more are still firing from batches you already closed, listed after them.`,
        "",
      );
    }
    for (const [index, single] of [...freshSingles, ...seenSingles].entries()) {
      if (
        seenSingles.length > 0 &&
        index === freshSingles.length &&
        freshSingles.length > 0
      ) {
        lines.push(
          "",
          "<details><summary>Still firing from earlier batches (already seen — no action implied)</summary>",
          "",
        );
      }
      const lane = single.firingLanes[0]?.lane ?? "?";
      const dead = result.lanes.deadcode?.entries.find(
        (e) => e.path === single.path,
      );
      const dup = result.lanes.duplication?.entries.find(
        (e) => e.path === single.path,
      );
      const sizeEntry = result.lanes.size?.entries.find(
        (e) => e.path === single.path,
      );
      let detail = "";
      if (lane === "deadcode" && dead) {
        // "unconsumed exports", never "dead" — round-7 found ~40% of
        // these are live symbols whose export keyword is the only dead
        // part, and the "dead:" label induced deletion advice.
        const label = dead.deadDetail.some((d) => d.internalUse === true)
          ? "unconsumed exports (some used internally — un-export, don't delete)"
          : "unconsumed exports";
        detail =
          dead.deadDetail.length > 0
            ? `${label}: ${dead.deadDetail.slice(0, 3).map((d) => d.name).join(", ")}${dead.deadDetail.length > 3 ? ` +${dead.deadDetail.length - 3}` : ""}`
            : "entire file unreferenced";
      } else if (lane === "duplication" && dup) {
        detail = `${dup.duplicatedLines} duplicated lines` + (dup.clusterFanOut > 0 ? ` across ${dup.clusterFanOut} partner(s)` : " (internal)");
      } else if (lane === "size" && sizeEntry) {
        detail = `${sizeEntry.codeLines} code lines (tier ${sizeEntry.tier})`;
      }
      lines.push(
        `- \`${single.path}\` — ${lane}${detail ? `: ${detail}` : ""}${precedentNote(result, single.path, [lane])} → \`.vibecompact/findings/${findingSlug(single.path)}.md\``,
      );
    }
    if (seenSingles.length > 0 && freshSingles.length > 0) {
      lines.push("", "</details>");
    }
    const dropped = [...droppedByLane.entries()].sort();
    if (dropped.length > 0) {
      const total = dropped.reduce((sum, [, n]) => sum + n, 0);
      lines.push(
        "",
        `_Cap: ${total} more single-lane firing${total === 1 ? "" : "s"} not packaged this run (per-lane cap ${result.config.maxReportItems}: ${dropped.map(([lane, n]) => `${lane} +${n}`).join(", ")}). They still fire in the machine data._`,
      );
    }
  }

  if (deletions.length > 0) {
    lines.push(
      "",
      "## Deletion candidates (single-signal, verify before acting)",
      "",
      "Below-gate but directly actionable once verified. Verification = repo-wide search for string references, dynamic imports, and runner configs.",
      "",
    );
    for (const d of deletions) {
      lines.push(
        `- \`${d.path}\` — ${d.reason}${precedentNote(result, d.path, ["consistency", "deadcode"])}`,
      );
    }
  }

  lines.push(
    "",
    "## Machine data",
    "",
    "Full lane entries, clone partners, scores, and ledger state: `.vibecompact/audit.json` on the data branch, `.vibecompact/out/audit.json` in a local run.",
  );
  return lines.join("\n") + "\n";
}
